services:
  backend:
    build:
      context: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app

  frontend:
    build:
      context: ./frontend
      target: build
      args:
        VITE_API_URL: "http://localhost:8000"
    working_dir: /app
    command: sh -c "(npm ci || npm install) && npm run dev -- --port 3000 --host 0.0.0.0"
    environment:
      - VITE_API_URL=http://localhost:8000
      - BACKEND_INTERNAL_URL=http://backend:8000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    depends_on:
      - backend

volumes:
  node_modules:
